name: "learning-workflow" 

on: 
  push:  
    branches:
      - 'feature/**'
      - main
jobs:
  Terraform_Install:
    name: Install Terraform
    runs-on: X64
    steps:
    - name: Installinstall
      run: echo ganesh_kadam 
    
    
      
