name: Terraform Workflow

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main
      - 'feature/*'
      
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5   # apni version set kar lena
      # Login to Azure using single secret 
      - name: Azure Login 
        uses: azure/login@v2 
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Dev Environment for feature branches
      - name: Terraform Init (Dev)
        if: startsWith(github.ref, 'refs/heads/feature/')
        working-directory: ./Env/Dev
        run: terraform init

      - name: Terraform Plan (Dev)
        if: startsWith(github.ref, 'refs/heads/feature/')
        working-directory: ./Env/Dev
        run: terraform plan

      # Prod Environment for main branch
      - name: Terraform Init (Prod)
        if: github.ref == 'refs/heads/main'
        working-directory: ./Env/Prod
        run: terraform init

      - name: Terraform Plan (Prod)
        if: github.ref == 'refs/heads/main'
        working-directory: ./Env/Prod
        run: terraform plan
