name: Terraform Workflow

on:
  push:
    branches:
      - 'feature/*'
      - main
  pull_request:
    branches:
      - main
      
jobs:
  terraform_plan:
    runs-on: self-hosted
    if: startsWith(github.ref, 'refs/heads/feature/')
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Azure Login 
        uses: azure/login@v2 
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform fmt (Dev)
        working-directory: ./Env/Dev
        run: terraform fmt -check -recursive 

      - name: Terraform validate (Dev)
        working-directory: ./Env/Dev
        run: terraform validate

      - name: Terraform Plan (Dev)
        working-directory: ./Env/Dev
        run: terraform plan


  apply-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: terraform_plan
    environment:
      name: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v3
      #   with:
      #     terraform_version: 1.7.5

      - name: Azure Login 
        uses: azure/login@v2 
        with: 
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init (Prod)
        working-directory: ./Env/Prod
        run: terraform init

      - name: Terraform Apply (Prod)
        working-directory: ./Env/Prod
        run: terraform apply -auto-approve
